/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyptgt;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author 01689
 */
public class Main extends javax.swing.JFrame {
    AddXeDap JpanelAddXeDap = new AddXeDap();
    ArrayList<XeDap> xeDaps = new ArrayList<>();
    ArrayList<XeMay> xeMays = new ArrayList<>();
    ArrayList<XeOtoCon> xeOtoCons = new ArrayList<>();
    ArrayList<XeOtoBanTai> xeOtoBanTais = new ArrayList<>();
    DefaultTableModel tableModel;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        searchbox = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        addXeDap = new javax.swing.JButton();
        AddXeMap = new javax.swing.JButton();
        AddXeOtoCon = new javax.swing.JButton();
        AddXeOtoBanTai = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textHangSanXuat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textNamSanXuat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textGiaThanh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textDungTichDongCo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textDungTichCop = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textTaiTrong = new javax.swing.JTextField();
        textChieuDaiThungXe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quan Ly Phuong Tien Giao Thong");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        title.setText("Phần mềm quản lý phương tiện giao thông");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        searchbox.setToolTipText("Tìm kiếm theo tên hãng");
        searchbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchboxMouseClicked(evt);
            }
        });
        searchbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchboxActionPerformed(evt);
            }
        });
        searchbox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchboxKeyReleased(evt);
            }
        });
        getContentPane().add(searchbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, 264, 30));

        search.setText("Tìm kiếm");
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchMouseClicked(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, -1, 30));

        addXeDap.setText("Thêm xe đạp");
        addXeDap.setActionCommand("addxeDap");
        addXeDap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addXeDapMouseClicked(evt);
            }
        });
        addXeDap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addXeDapActionPerformed(evt);
            }
        });
        getContentPane().add(addXeDap, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        AddXeMap.setText("Thêm xe máy");
        AddXeMap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddXeMapMouseClicked(evt);
            }
        });
        getContentPane().add(AddXeMap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, -1, -1));

        AddXeOtoCon.setText("Thêm xe Ô tô con");
        AddXeOtoCon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddXeOtoConMouseClicked(evt);
            }
        });
        getContentPane().add(AddXeOtoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, -1));

        AddXeOtoBanTai.setText("Thêm xe Ô tô bán tải");
        AddXeOtoBanTai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddXeOtoBanTaiMouseClicked(evt);
            }
        });
        getContentPane().add(AddXeOtoBanTai, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        Exit.setText("Thoát chương trình");
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 610, -1, -1));

        jLabel1.setText("Tên: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        textTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTenActionPerformed(evt);
            }
        });
        getContentPane().add(textTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 65, 167, -1));

        jLabel2.setText("Hãng sản xuất : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        textHangSanXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textHangSanXuatActionPerformed(evt);
            }
        });
        getContentPane().add(textHangSanXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 113, 167, -1));

        jLabel3.setText("Năm sản Xuất :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 168, -1, -1));
        getContentPane().add(textNamSanXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 165, 167, -1));

        jLabel4.setText("Giá thành: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 229, -1, -1));
        getContentPane().add(textGiaThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 226, 167, -1));

        jLabel5.setText("Dung tích động cơ: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 278, -1, -1));
        getContentPane().add(textDungTichDongCo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 275, 167, -1));

        jLabel6.setText("Dung tích cốp: ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 318, -1, -1));

        textDungTichCop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDungTichCopActionPerformed(evt);
            }
        });
        getContentPane().add(textDungTichCop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 315, 167, -1));

        jLabel7.setText("Tải trọng: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 379, -1, -1));

        jLabel8.setText("Chiều dài thùng xe: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 429, -1, -1));
        getContentPane().add(textTaiTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 376, 166, -1));
        getContentPane().add(textChieuDaiThungXe, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 426, 166, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tên", "Hãng sản xuất", "Năm sản xuất", "Giá thành", "Dung tích động cơ", "Dung tích cốp", "Tải trọng", "Chiều dài thùng xe", "Thuế trước bạ"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 870, 470));

        jLabel9.setText("XD: xe dap, XM: xe may, OC: xe Oto con, BT: xe Oto BanTai");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 330, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        textTen.setText("");
        textTaiTrong.setText("");
        textNamSanXuat.setText("");
        textHangSanXuat.setText("");
        textGiaThanh.setText("");
        textDungTichDongCo.setText("");
        textDungTichCop.setText("");
        textChieuDaiThungXe.setText("");
        
    }
    private void addXeDapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addXeDapActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_addXeDapActionPerformed

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMouseClicked

    private void searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseClicked

        // TODO add your handling code here:
    }//GEN-LAST:event_searchMouseClicked

    private void searchboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchboxMouseClicked
        searchbox.setText("");
    }//GEN-LAST:event_searchboxMouseClicked

    private void addXeDapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addXeDapMouseClicked
        // TODO add your handling code here:
        XeDap xedap = new XeDap();
        if(textTen.getText().equals("")||textNamSanXuat.getText().equals("")||textHangSanXuat.getText().equals("")||textGiaThanh.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Chưa đủ dữ liệu mời bạn nhập lại");
        }else{
            xedap.setName("XD-"+textTen.getText());
            xedap.setHangSanXuat(textHangSanXuat.getText());
            xedap.setThueTruocBa((float) xedap.TinhThueTruocBa(xedap.getGiaTien(), 1));
            try {
                xedap.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xedap.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Bạn đã nhập sai xin vui lòng nhập lại");
                xedap.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xedap.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
            }
            xeDaps.add(xedap);
            tableModel.addRow(new Object[]{
                xedap.getName(),xedap.getHangSanXuat(),xedap.getNamSanXuat(),xedap.getGiaTien(),"","","","",xedap.getThueTruocBa()
            });
            reset();    
            
        }
    }//GEN-LAST:event_addXeDapMouseClicked

    private void AddXeMapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddXeMapMouseClicked
        // TODO add your handling code here:
        XeMay xemay = new XeMay();
        if(textTen.getText().equals("")||textNamSanXuat.getText().equals("")||textHangSanXuat.getText().equals("")
            ||textGiaThanh.getText().equals("")||textDungTichDongCo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Chưa đủ dữ liệu mời bạn nhập lại");
        }else{
            xemay.setName("XM-"+textTen.getText());
            xemay.setHangSanXuat(textHangSanXuat.getText());
            try {
                xemay.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xemay.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xemay.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "bạn đã nhập sai xin vui lòng nhập lại");
                xemay.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xemay.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xemay.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
            }          
            xemay.setThueTruocBa((float) xemay.TinhThueTruocBa(xemay.getGiaTien(),(5/100)));
           // System.out.println(xemay.TinhThueTruocBa(xemay.getGiaTien(),(float) (5/100)));
            xeMays.add(xemay);
            tableModel.addRow(new Object[]{
                xemay.getName(),xemay.getHangSanXuat(),xemay.getNamSanXuat(),xemay.getGiaTien(),xemay.getDungTichDongCo(),"","","",xemay.getThueTruocBa()
            });
            reset();            
        }

    }//GEN-LAST:event_AddXeMapMouseClicked

    private void AddXeOtoConMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddXeOtoConMouseClicked
        XeOtoCon xeOtoCon = new XeOtoCon();
        if(textTen.getText().equals("")||textNamSanXuat.getText().equals("")||textHangSanXuat.getText().equals("")
            ||textGiaThanh.getText().equals("")||textDungTichDongCo.getText().equals("")||textDungTichCop.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Chưa đủ dữ liệu mời bạn nhập lại");
        }else{
            xeOtoCon.setName("OC-"+textTen.getText());
            xeOtoCon.setHangSanXuat(textHangSanXuat.getText());
            try {
                xeOtoCon.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xeOtoCon.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xeOtoCon.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
                xeOtoCon.setDungTichCop(Integer.parseInt(textDungTichCop.getText()));                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "bạn đã nhập sai xin vui lòng nhập lại");
                xeOtoCon.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xeOtoCon.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xeOtoCon.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
                xeOtoCon.setDungTichCop(Integer.parseInt(textDungTichCop.getText()));  
            }

            xeOtoCon.setThueTruocBa((float) xeOtoCon.TinhThueTruocBa(xeOtoCon.getGiaTien(), (12/100)));
            xeOtoCons.add(xeOtoCon);
            tableModel.addRow(new Object[]{
                xeOtoCon.getName(),xeOtoCon.getHangSanXuat(),xeOtoCon.getNamSanXuat(),xeOtoCon.getGiaTien(),xeOtoCon.getDungTichDongCo(),
                xeOtoCon.getDungTichCop(),"","",xeOtoCon.getThueTruocBa()
            });
            reset();        
        }

    }//GEN-LAST:event_AddXeOtoConMouseClicked

    private void AddXeOtoBanTaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddXeOtoBanTaiMouseClicked
        XeOtoBanTai xeOtoBanTai = new XeOtoBanTai();
        if(textTen.getText().equals("")||textNamSanXuat.getText().equals("")||textHangSanXuat.getText().equals("")
            ||textGiaThanh.getText().equals("")||textDungTichDongCo.getText().equals("")||textTaiTrong.getText().equals("")||textChieuDaiThungXe.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Chưa đủ dữ liệu mời bạn nhập lại");
        }else{ 
            xeOtoBanTai.setName("BT-"+textTen.getText());
            xeOtoBanTai.setHangSanXuat(textHangSanXuat.getText());
            try {
                xeOtoBanTai.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xeOtoBanTai.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xeOtoBanTai.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
                xeOtoBanTai.setTaiTrong(Integer.parseInt(textTaiTrong.getText()));
                xeOtoBanTai.setChieuDaiThungXe(Integer.parseInt(textChieuDaiThungXe.getText()));               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "bạn đã nhập sai xin vui lòng nhập lại");
                xeOtoBanTai.setNamSanXuat(Integer.parseInt(textNamSanXuat.getText()));
                xeOtoBanTai.setGiaTien(Double.parseDouble(textGiaThanh.getText()));
                xeOtoBanTai.setDungTichDongCo(Integer.parseInt(textDungTichDongCo.getText()));
                xeOtoBanTai.setTaiTrong(Integer.parseInt(textTaiTrong.getText()));
                xeOtoBanTai.setChieuDaiThungXe(Integer.parseInt(textChieuDaiThungXe.getText()));                 
            }

            xeOtoBanTai.setThueTruocBa((float) xeOtoBanTai.TinhThueTruocBa(xeOtoBanTai.getGiaTien(), (float) (7.5/100)));
            xeOtoBanTais.add(xeOtoBanTai);
            tableModel.addRow(new Object[]{
                xeOtoBanTai.getName(),xeOtoBanTai.getHangSanXuat(),xeOtoBanTai.getNamSanXuat(),xeOtoBanTai.getGiaTien(),xeOtoBanTai.getDungTichDongCo()
                ,"",xeOtoBanTai.getTaiTrong(),xeOtoBanTai.getChieuDaiThungXe(),xeOtoBanTai.getThueTruocBa()
            });
            reset();        
        }    
    }//GEN-LAST:event_AddXeOtoBanTaiMouseClicked

    private void textDungTichCopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDungTichCopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDungTichCopActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitActionPerformed

    private void textTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTenActionPerformed

    private void textHangSanXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textHangSanXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textHangSanXuatActionPerformed

    private void searchboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchboxActionPerformed

    private void searchboxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchboxKeyReleased
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchbox.getText().trim()));
    }//GEN-LAST:event_searchboxKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddXeMap;
    private javax.swing.JButton AddXeOtoBanTai;
    private javax.swing.JButton AddXeOtoCon;
    private javax.swing.JButton Exit;
    private javax.swing.JButton addXeDap;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchbox;
    private javax.swing.JTextField textChieuDaiThungXe;
    private javax.swing.JTextField textDungTichCop;
    private javax.swing.JTextField textDungTichDongCo;
    private javax.swing.JTextField textGiaThanh;
    private javax.swing.JTextField textHangSanXuat;
    private javax.swing.JTextField textNamSanXuat;
    private javax.swing.JTextField textTaiTrong;
    private javax.swing.JTextField textTen;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
